#' @title Load Synthea Tables.
#'
#' @description This function populates all Synthea tables.
#'
#' @details This function assumes \cr\code{createSyntheaTables()} has already been run.  Additionally,
#'              this function assumes the data files used to populate the tables are csv files generated by
#'              running the basic setup (creating a database with 1000 people):
#'                  \cr\code{git clone https://github.com/synthetichealth/synthea.git}
#'                  \cr\code{cd synthea}
#'                  \cr\code{./gradlew build check test}
#'                  \cr\code{./run_synthea -p 1000}
#'
#'               You can enable csv records in src/main/resources/synthea.properties by setting exporter.csv.export = true.
#'               As of the time of this writing the csv files can be found at synthe/output/csv.
#'               For more details: \href{https://github.com/synthetichealth/synthea/wiki/Basic-Setup-and-Running}{Synthea Basic Setup}
#'
#' @param connectionDetails  An R object of type\cr\code{connectionDetails} created using the
#'                                     function \code{createConnectionDetails} in the
#'                                     \code{DatabaseConnector} package.
#' @param syntheaSchema  The name of the database schema that will contain the Synthea
#'                                     instance.  Requires read and write permissions to this database. On SQL
#'                                     Server, this should specifiy both the database and the schema,
#'                                     so for example 'cdm_instance.dbo'.
#' @param syntheaFileLoc     The location of the Synthea csv files created by running the executable run_synthea.
#' @param bulkLoad       Boolean flag indicating whether or not to use bulk loading (if possible).  Default is FALSE.
#'
#'@export


LoadSyntheaTables <-
  function(connectionDetails,
           syntheaSchema,
           syntheaFileLoc,
           bulkLoad = FALSE)
{

   csvList <- list.files(syntheaFileLoc, pattern = "*.csv")
	
   conn <- DatabaseConnector::connect(connectionDetails)

   for (csv in csvList) {
      batch_size <- 100000

      writeLines(paste0("Loading: ", csv))

      fin <- file(paste0(syntheaFileLoc,"/",csv), open = "r")
      # read header first:
      header <- paste(readLines(fin, n = 1, warn = FALSE),"\n",sep="")
      header <- data.table::fread(text = header, stringsAsFactors = FALSE, header = FALSE, sep = ",", na.strings = "")
      header <- as.matrix(header)[1,]

      while (length(batch <- readLines(fin, n = batch_size, warn = FALSE)) > 0) {
         if (!endsWith(batch, "\n")) {
            batch <- paste(batch, "\n", sep="")
         }
         batch <- data.table::fread(text=batch, stringsAsFactors = FALSE, header = FALSE, sep = ",", na.strings = "", col.names=header)

         # experiencing type conversion errors and need to explicitly case some columns
         if ("START"       %in% colnames(batch))
            batch$START        <-
            as.Date(batch$START, format = "%Y-%m-%d")
         if ("STOP"        %in% colnames(batch))
            batch$STOP         <-
            as.Date(batch$STOP, format = "%Y-%m-%d")
         if ("DATE"        %in% colnames(batch))
            batch$DATE         <-
            as.Date(batch$DATE, format = "%Y-%m-%d")
         if ("BIRTHDATE"   %in% colnames(batch))
            batch$BIRTHDATE    <-
            as.Date(batch$BIRTHDATE, format = "%Y-%m-%d")
         if ("DEATHDATE"   %in% colnames(batch))
            batch$DEATHDATE    <-
            as.Date(batch$DEATHDATE, format = "%Y-%m-%d")
         if ("CODE"        %in% colnames(batch))
            batch$CODE         <- as.character(batch$CODE)
         if ("REASONCODE"  %in% colnames(batch))
            batch$REASONCODE   <-
            as.character(batch$REASONCODE)
         if ("PHONE"       %in% colnames(batch))
            batch$PHONE        <-
            as.character(batch$PHONE)
         if ("UTILIZATION" %in% colnames(batch))
            batch$UTILIZATION  <-
            as.numeric(batch$UTILIZATION)

         suppressWarnings({
                DatabaseConnector::insertTable(
                  conn,
                  tableName = paste0(syntheaSchema, ".", strsplit(csv, "[.]")[[1]][1]),
                  data = as.data.frame(batch),
                  dropTableIfExists = FALSE,
                  createTable = FALSE,
                  bulkLoad = bulkLoad,
                  progressBar = TRUE
                )
         })
      }
      close(fin)
   }
   on.exit(DatabaseConnector::disconnect(conn))
}